# Generated by Django 5.2.17 on 2026-08-30 16:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import privacy.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('jurisdiction', models.CharField(choices=[('vn_current', 'Việt Nam hiện hành'), ('vn_nd13_history', 'NĐ 13/2023 (đối chiếu lịch sử)'), ('gdpr', 'GDPR'), ('internal', 'Quy tắc vận hành nội bộ')], max_length=24)),
                ('description', models.TextField(blank=True)),
                ('legal_review_required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['jurisdiction', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('suspended', 'Tạm dừng'), ('archived', 'Lưu trữ')], default='active', max_length=16)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('gdpr_assessment_required', models.BooleanField(default=False, help_text='Cờ đánh giá phạm vi; không tự kết luận GDPR áp dụng.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DSARCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=privacy.models._case_reference, editable=False, max_length=24)),
                ('subject_email', models.EmailField(blank=True, max_length=254)),
                ('request_type', models.CharField(choices=[('access', 'Yêu cầu truy cập'), ('rectification', 'Yêu cầu chỉnh sửa'), ('portability', 'Yêu cầu cung cấp dữ liệu'), ('erasure', 'Yêu cầu xóa'), ('restriction', 'Yêu cầu hạn chế xử lý'), ('objection', 'Yêu cầu phản đối'), ('withdrawal', 'Rút sự đồng ý'), ('protection', 'Yêu cầu bảo vệ dữ liệu')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('submitted', 'Đã tiếp nhận'), ('identity_verified', 'Đã xác thực danh tính'), ('in_review', 'Đang xử lý'), ('pending_officer_approval', 'Chờ Privacy Officer phê duyệt'), ('approved', 'Đã phê duyệt'), ('rejected', 'Từ chối'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='draft', max_length=32)),
                ('sla_state', models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('on_track', 'Đúng hạn'), ('due_soon', 'Sắp đến hạn'), ('extended', 'Đã gia hạn'), ('overdue', 'Quá hạn')], default='not_started', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('extended_due_at', models.DateTimeField(blank=True, null=True)),
                ('extension_reason', models.TextField(blank=True)),
                ('extension_granted_at', models.DateTimeField(blank=True, null=True)),
                ('requires_officer_approval', models.BooleanField(default=True)),
                ('officer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('anonymised_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dsar_cases', to=settings.AUTH_USER_MODEL)),
                ('officer_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dsar_cases', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsar_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Nghiêm trọng')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('detected', 'Đã phát hiện'), ('investigating', 'Đang điều tra'), ('pending_officer_approval', 'Chờ Privacy Officer phê duyệt'), ('approved', 'Đã phê duyệt phương án'), ('reported', 'Đã tạo bản nháp thông báo'), ('contained', 'Đã cô lập'), ('closed', 'Đã đóng')], default='detected', max_length=32)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_due_at', models.DateTimeField(blank=True, null=True)),
                ('notification_draft', models.TextField(blank=True)),
                ('containment_notes', models.TextField(blank=True)),
                ('officer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('officer_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_incidents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='NoticeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('version', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã công bố'), ('retired', 'Đã thay thế')], default='draft', max_length=16)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=250)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['title', '-effective_at'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('data_subject', 'Chủ thể dữ liệu'), ('case_agent', 'Chuyên viên xử lý hồ sơ'), ('privacy_officer', 'Privacy Officer'), ('tenant_admin', 'Quản trị viên tổ chức'), ('platform_auditor', 'Kiểm toán viên nền tảng')], default='data_subject', max_length=24)),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('invited', 'Đã mời'), ('suspended', 'Tạm dừng')], default='active', max_length=16)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('imposed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True)),
                ('dsar_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to='privacy.dsarcase')),
                ('imposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposed_legal_holds', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('entity_type', models.CharField(choices=[('controller', 'Bên kiểm soát dữ liệu'), ('processor', 'Bên xử lý dữ liệu'), ('joint_controller', 'Đồng kiểm soát dữ liệu'), ('other', 'Khác')], max_length=20)),
                ('country_code', models.CharField(default='VN', max_length=2)),
                ('registration_reference', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('file_reference', models.CharField(blank=True, max_length=300)),
                ('digest_sha256', models.CharField(blank=True, max_length=64)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_incident_evidence', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='privacy.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['collected_at'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=180)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('json', 'JSON')], max_length=8)),
                ('status', models.CharField(choices=[('pending_approval', 'Chờ phê duyệt'), ('approved', 'Đã phê duyệt'), ('generating', 'Đang tạo'), ('ready', 'Đã tạo, sẵn sàng tải'), ('expired', 'Đã hết hạn'), ('revoked', 'Đã thu hồi')], default='pending_approval', max_length=20)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('document_sha256', models.CharField(blank=True, max_length=64)),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(default=privacy.models._export_expiry)),
                ('requires_reauthentication', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exports', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_artifacts', to='privacy.dsarcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='DSARCaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('open', 'Chưa xử lý'), ('in_progress', 'Đang xử lý'), ('blocked', 'Bị chặn'), ('done', 'Hoàn tất')], default='open', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsar_tasks', to=settings.AUTH_USER_MODEL)),
                ('dsar_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='privacy.dsarcase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['due_at', 'created_at'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=70)),
                ('sensitivity', models.CharField(choices=[('personal', 'Dữ liệu cá nhân'), ('sensitive', 'Dữ liệu cá nhân nhạy cảm'), ('children', 'Dữ liệu của trẻ em'), ('technical', 'Dữ liệu kỹ thuật')], default='personal', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveBigIntegerField(editable=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event_type', models.CharField(max_length=120)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('previous_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('event_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['organization_id', 'sequence'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.SlugField(max_length=70)),
                ('legal_role', models.CharField(choices=[('controller', 'Bên kiểm soát dữ liệu'), ('processor', 'Bên xử lý dữ liệu'), ('joint_controller', 'Đồng kiểm soát dữ liệu')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('active', 'Đang xử lý'), ('paused', 'Tạm dừng'), ('retired', 'Ngừng áp dụng')], default='draft', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('retention_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('gdpr_applicable', models.BooleanField(default=False)),
                ('involves_cross_border_transfer', models.BooleanField(default=False)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_activities', to='privacy.legalentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ImpactDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('dossier_type', models.CharField(choices=[('dpia', 'Đánh giá tác động xử lý'), ('cross_border', 'Hồ sơ chuyển dữ liệu xuyên biên giới'), ('incident', 'Đánh giá sự cố')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('in_review', 'Đang đánh giá'), ('ready_for_approval', 'Chờ phê duyệt'), ('approved', 'Đã phê duyệt'), ('rejected', 'Từ chối')], default='draft', max_length=24)),
                ('risk_summary', models.TextField(blank=True)),
                ('mitigations', models.TextField(blank=True)),
                ('assessment_reference', models.CharField(blank=True, max_length=180)),
                ('requires_legal_review', models.BooleanField(default=True)),
                ('officer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('officer_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_impact_dossiers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('processing_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_dossiers', to='privacy.processingactivity')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingActivityDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_links', to='privacy.datacategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('processing_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='privacy.processingactivity')),
            ],
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=70)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingActivityPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('processing_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_links', to='privacy.processingactivity')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_links', to='privacy.processingpurpose')),
            ],
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='NoticePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_links', to='privacy.noticeversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notice_links', to='privacy.processingpurpose')),
            ],
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('granted', 'Đồng ý'), ('withdrawn', 'Đã rút đồng ý'), ('restricted', 'Đã hạn chế xử lý')], max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_reference', models.CharField(blank=True, max_length=250)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_consent_events', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_events', to=settings.AUTH_USER_MODEL)),
                ('notice_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_events', to='privacy.noticeversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_events', to='privacy.processingpurpose')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('target', models.CharField(choices=[('dsar_case', 'Hồ sơ DSAR'), ('export_artifact', 'Tệp xuất')], max_length=24)),
                ('retention_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('action', models.CharField(choices=[('anonymise', 'Ẩn danh hóa'), ('revoke', 'Thu hồi tệp')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('processing_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_policies', to='privacy.processingactivity')),
            ],
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('data_subject', 'Chủ thể dữ liệu'), ('case_agent', 'Chuyên viên xử lý hồ sơ'), ('privacy_officer', 'Privacy Officer'), ('tenant_admin', 'Quản trị viên tổ chức'), ('platform_auditor', 'Kiểm toán viên nền tảng')], max_length=24)),
                ('scope', models.CharField(choices=[('organization', 'Toàn tổ chức'), ('processing_activity', 'Hoạt động xử lý'), ('dsar', 'Hồ sơ DSAR'), ('incident', 'Sự cố')], default='organization', max_length=24)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='privacy.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('processing_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='privacy.processingactivity')),
            ],
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=40)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Mốc vận hành bằng ngày dương lịch nếu quy tắc quy định một thời hạn.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('source_url', models.URLField(blank=True)),
                ('source_reference', models.CharField(blank=True, max_length=250)),
                ('is_current', models.BooleanField(default=True)),
                ('legal_review_required', models.BooleanField(default=True)),
                ('legal_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='privacy.legalrule')),
            ],
            options={
                'ordering': ['legal_rule__code', '-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='notification_rule_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='privacy.ruleversion'),
        ),
        migrations.CreateModel(
            name='ExemptionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('assessing', 'Đang đánh giá'), ('eligible', 'Có thể áp dụng miễn trừ'), ('not_eligible', 'Không đủ điều kiện'), ('legal_review', 'Cần legal review')], default='draft', max_length=16)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_revenue_vnd', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('basis', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exemption_assessments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('processing_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemption_assessments', to='privacy.processingactivity')),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exemption_assessments', to='privacy.ruleversion')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.AddField(
            model_name='dsarcase',
            name='rule_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dsar_cases', to='privacy.ruleversion'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('destination_country', models.CharField(max_length=2)),
                ('legal_basis', models.CharField(blank=True, max_length=180)),
                ('data_flow_description', models.TextField(blank=True)),
                ('contract_reference', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('in_review', 'Đang đánh giá'), ('ready_for_approval', 'Đủ hồ sơ, chờ phê duyệt'), ('approved', 'Đã phê duyệt'), ('blocked', 'Bị chặn')], default='draft', max_length=24)),
                ('officer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('exemption_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='privacy.exemptionassessment')),
                ('impact_dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='privacy.impactdossier')),
                ('officer_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='TransferDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_links', to='privacy.datacategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='privacy.transfer')),
            ],
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('country_code', models.CharField(max_length=2)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('service_description', models.TextField(blank=True)),
                ('dpa_in_place', models.BooleanField(default=False)),
                ('contract_reference', models.CharField(blank=True, max_length=180)),
                ('contract_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('processes_sensitive_data', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('under_review', 'Đang đánh giá'), ('approved', 'Đã phê duyệt'), ('suspended', 'Tạm dừng')], default='draft', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='privacy.vendor'),
        ),
        migrations.CreateModel(
            name='Subprocessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('country_code', models.CharField(max_length=2)),
                ('service_description', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_subprocessors', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='privacy.organization')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocessors', to='privacy.vendor')),
            ],
            options={
                'ordering': ['vendor__name', 'name'],
            },
            managers=[
                ('objects', privacy.models.TenantScopedManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='noticeversion',
            constraint=models.UniqueConstraint(fields=('organization', 'title', 'version'), name='privacy_notice_org_title_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='privacy_mem_user_id_1ce5b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='privacy_membership_org_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='legalhold',
            index=models.Index(fields=['organization', 'active', 'subject_email'], name='privacy_leg_organiz_a8fd21_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='privacy_entity_org_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='privacy_one_primary_entity_per_org'),
        ),
        migrations.AddIndex(
            model_name='exportartifact',
            index=models.Index(fields=['organization', 'status', 'expires_at'], name='privacy_exp_organiz_7e5dbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='datacategory',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='privacy_category_org_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.UniqueConstraint(fields=('organization', 'sequence'), name='privacy_audit_org_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processingactivity',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='privacy_activity_org_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processingactivitydatacategory',
            constraint=models.UniqueConstraint(fields=('organization', 'processing_activity', 'data_category'), name='privacy_activity_category_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processingpurpose',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='privacy_purpose_org_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processingactivitypurpose',
            constraint=models.UniqueConstraint(fields=('organization', 'processing_activity', 'purpose'), name='privacy_activity_purpose_uniq'),
        ),
        migrations.AddConstraint(
            model_name='noticepurpose',
            constraint=models.UniqueConstraint(fields=('organization', 'notice_version', 'purpose'), name='privacy_notice_purpose_uniq'),
        ),
        migrations.AddIndex(
            model_name='consentevent',
            index=models.Index(fields=['organization', 'subject_email', 'purpose', '-occurred_at'], name='privacy_con_organiz_197715_idx'),
        ),
        migrations.AddConstraint(
            model_name='retentionpolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='privacy_retention_policy_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('organization', 'membership', 'role', 'scope', 'processing_activity'), name='privacy_role_assignment_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ruleversion',
            constraint=models.UniqueConstraint(fields=('legal_rule', 'version'), name='privacy_rule_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'status', 'notification_due_at'], name='privacy_inc_organiz_2361d1_idx'),
        ),
        migrations.AddIndex(
            model_name='dsarcase',
            index=models.Index(fields=['organization', 'status', 'due_at'], name='privacy_dsa_organiz_fabe02_idx'),
        ),
        migrations.AddIndex(
            model_name='dsarcase',
            index=models.Index(fields=['organization', 'subject_email'], name='privacy_dsa_organiz_710f1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dsarcase',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='privacy_dsar_org_reference_uniq'),
        ),
        migrations.AddConstraint(
            model_name='transferdatacategory',
            constraint=models.UniqueConstraint(fields=('organization', 'transfer', 'data_category'), name='privacy_transfer_category_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='privacy_vendor_org_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subprocessor',
            constraint=models.UniqueConstraint(fields=('organization', 'vendor', 'name'), name='privacy_subprocessor_uniq'),
        ),
    ]
